### ISSUE TITLE
Unable to start the SpaceBukkit plugin

### ISSUE THREAD

**Issue by greatman** [XereoNet/SpaceBukkit#110]
Getting this error:
2012-02-04 15:41:42 [INFO] [SpaceBukkit] Loading SpaceBukkit v1.0.
2012-02-04 15:41:42 [SEVERE] Error occurred while enabling SpaceBukkit v1.0 (Is it up to date?): com/google/gson/GsonBuilder
java.lang.NoClassDefFoundError: com/google/gson/GsonBuilder
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.getDeclaredMethod(Unknown Source)
        at me.neatmonster.spacebukkit.plugins.PluginsManager.getJAR(PluginsManager.java:34)
        at me.neatmonster.spacebukkit.plugins.PluginsManager.<init>(PluginsManager.java:53)
        at me.neatmonster.spacebukkit.SpaceBukkit.onEnable(SpaceBukkit.java:73)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:231)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:1057)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:379)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:191)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:174)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:356)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:343)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:175)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:407)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:465)
Caused by: java.lang.ClassNotFoundException: com.google.gson.GsonBuilder
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 16 more

**Comment by maniacmusic** [comment]
This issue can be closed, it was fixed in SpaceBukkit build 23

**Comment by greatman** [comment]
Closed it is!
