### ISSUE TITLE
Can't use restart server

### ISSUE THREAD

**Issue by watar** [XereoNet/SpaceBukkit#117]
When trying to restart the server this shows up in console:
me.neatmonster.spaceapi.actions.InvalidArgumentsException: 1 arguments expected, not 0 for method restart.
        at me.neatmonster.spaceapi.actions.ActionsManager.execute(ActionsManager.java:82)
        at me.neatmonster.spacertk.PanelListener.interpret(PanelListener.java:48)
        at me.neatmonster.spacertk.PanelListener.run(PanelListener.java:127)

and then it halts. I can press stop server and wait for it to stop and press start and the server is restarted but Restart on it's own doesn't work.

**Comment by ray73864** [comment]
I too get this issue, i thought maybe i had just installed the system incorrectly, good to know someone else has the issue.

**Comment by Antariano** [comment]
Fixed
