### ISSUE TITLE
Error on console when the server is shutting down or restarting

### ISSUE THREAD

**Issue by lucasdidur** [XereoNet/SpaceBukkit#139]
09:05:02 [INFO] ----------------------------------------------------------
09:05:02 [INFO] |             SpaceBukkit is now disabled!               |
09:05:02 [INFO] ----------------------------------------------------------
09:05:02 [SEVERE] java.net.SocketException: Socket closed
09:05:02 [SEVERE]       at java.net.PlainSocketImpl.socketAccept(Native Method)
09:05:02 [SEVERE]       at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
09:05:02 [SEVERE]       at java.net.ServerSocket.implAccept(ServerSocket.java:522)
09:05:02 [SEVERE]       at java.net.ServerSocket.accept(ServerSocket.java:490)
09:05:02 [SEVERE]       at me.neatmonster.spacebukkit.PanelListener.run(PanelListener.java:86)

**Comment by crckdns** [comment]
yep, I'm having the same issue..seems to be because the connection is getting lost (as expected^^) while restart/shutdown ..
not a real bug, but cosmetic issue..
