### ISSUE TITLE
NullPointerException on enable

### ISSUE THREAD

**Issue by lucasdidur** [XereoNet/SpaceBukkit#165]
I'm using

CraftBukkit version git-Bukkit-jenkins-CraftBukkit-93 (MC: 1.2.5) (Implementing API version 1.2.5-R1.3-MCPC-SNAPSHOT)

By Tekkit 3.0.3 - http://www.technicpack.net/tekkit/

And can't enable the plugin.

2012-05-29 11:53:12 [INFO] [SpaceBukkit] Enabling SpaceBukkit v0.1
2012-05-29 11:53:12 [SEVERE] Error occurred while enabling SpaceBukkit v0.1 (Is it up to date?)
java.lang.NullPointerException
    at me.neatmonster.spacebukkit.plugins.PluginsManager.getJAR(PluginsManager.java:33)
    at me.neatmonster.spacebukkit.plugins.PluginsManager.<init>(PluginsManager.java:61)
    at me.neatmonster.spacebukkit.SpaceBukkit.onEnable(SpaceBukkit.java:89)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:386)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:262)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:244)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:375)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:362)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:191)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:426)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

**Comment by tips48** [comment]
Your not the only one getting this error...Hopefully there will be a fix soon.

You can contribute any more information you have here: http://forums.xereo.net/threads/error-while-enabling-spacebukkit.395/

**Comment by roblabla** [comment]
Error in file https://github.com/SpaceDev/SpaceBukkit/edit/master/src/me/neatmonster/spacebukkit/plugins/PluginsManager.java
at line 44
        while (!(currentClass.equals(JavaPlugin.class))) {

Guess what happens if a plugin does NOT subclass JavaPlugin ? Well, it enters an infinite loop ! 
https://github.com/SpaceDev/SpaceBukkit/pull/194 this will fix.
