### ISSUE TITLE
BukGet plugin installation not working

### ISSUE THREAD

**Issue by minthost** [XereoNet/SpaceBukkit#204]
Location: Control panel, Plugins Section, BukGet
Browser: Chrome
Webserver: Apache 2
SpaceBukkit version: 1.2.1
Minecraft Server: Regular, recommended Bukkit
OS (Web):Apache 2.2, Debian Squeeze

SpaceModule #81 
RTK R10 14.5

With recommended spacebukkit.jar:

Plugin installation via BukGet interface does not simply work. Everything seems working, I can see plugin names, browse descriptions etc, but when it comes to installing - it wont work. It tells me that plugin is installed and I need to restart the server, but it is not. No JAR downloaded, console is clean. 

With development version of spacebukkit.jar

Port 2012:

Could not ping port. is it forwarded correctly, is it being used at all by SpaceBukkit?

Console gives these errors:

Startup:
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at me.neatmonster.spacemodule.SpaceModule.load(SpaceModule.java:269)
        at me.neatmonster.spacemodule.SpaceModule.onEnable(SpaceModule.java:402)
        at com.drdanick.McRKit.module.Module.startModule(Module.java:45)
        at com.drdanick.McRKit.module.ModuleManager.handleToolkitStateEvent(ModuleManager.java:66)
        at com.drdanick.McRKit.McRKitLauncher.<init>(McRKitLauncher.java:155)
        at com.drdanick.McRKit.McRKitLauncher.main(McRKitLauncher.java:109)
Caused by: java.lang.NoSuchMethodError: me.neatmonster.spacemodule.SpaceModule.getEdt()Lcom/drdanick/rtoolkit/s
ystem/EventDispatcher;
        at me.neatmonster.spacertk.SpaceRTK.<init>(SpaceRTK.java:81)
        ... 10 more

and

2013-03-13 05:21:38 [INFO] [SpaceBukkit] Enabling SpaceBukkit v1.2
2013-03-13 05:21:38 [SEVERE] java.lang.NullPointerException
2013-03-13 05:21:38 [SEVERE]    at com.drdanick.rtoolkit.system.EventDispatcher.<init>(EventDispatcher.java:44)
2013-03-13 05:21:38 [SEVERE]    at me.neatmonster.spacebukkit.SpaceBukkit.onEnable(SpaceBukkit.java:142)
2013-03-13 05:21:38 [SEVERE]    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
2013-03-13 05:21:38 [SEVERE]    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:4
57)
2013-03-13 05:21:38 [SEVERE]    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:
381)
2013-03-13 05:21:38 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:282)
2013-03-13 05:21:38 [SEVERE]    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:26
4)
2013-03-13 05:21:38 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.j(MinecraftServer.java:321)
2013-03-13 05:21:38 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.e(MinecraftServer.java:300)
2013-03-13 05:21:38 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.a(MinecraftServer.java:259)
2013-03-13 05:21:38 [SEVERE]    at net.minecraft.server.v1_4_R1.DedicatedServer.init(DedicatedServer.java:149)
2013-03-13 05:21:38 [SEVERE]    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:399)
2013-03-13 05:21:38 [SEVERE]    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

**Comment by Idealcoder** [comment]
I have same problem too running Debian. Installing via URL works for me though. What makes me clueless is that surly installing via URL and bukget is the same process?

**Comment by kylebartz** [comment]
Same here

**Comment by Jenjen1324** [comment]
Same here
