### ISSUE TITLE
Setting the Server Properties doesn't work (Windows)

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#47]
Ihave change the Server Properties. After restart none of the changes are made.The Web and Bukkit has root rights.

Consoles gives me following Error:

java.io.FileNotFoundException: server.properties (Der Vorgang ist bei einer Datei mit einem geöffneten Bereich, der einem Benutzer zugeordnet ist, nicht anwendbar)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileWriter.<init>(Unknown Source)
        at me.neatmonster.spacebukkitrtk.web.Executor.setFileContents(Executor.java:375)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:71)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:33)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71)

**Comment by NeatMonster** [comment]
@GoldenIrony Can you try again with latest builds please? http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by JamyDev** [comment]
Issue on Windows right?

(planned for 1.05)

**Comment by JamyDev** [comment]
New system works fine on linux; on windows though, I get this error: 
http://pastie.org/3097291

info was sent using setPropertiesFile using these arguments:
http://pastie.org/3097295

@NeatMonster This one's for you :S

**Comment by NeatMonster** [comment]
@JamyDev Do you not remember? It's the 'file already in use' issue.

**Comment by JamyDev** [comment]
It looks different, it says file not found :3

**Comment by NeatMonster** [comment]
It's the same. I found the issue. When you calling fileGetContents, I don't know why but it keeps using the file so obviously editPropertiesFile can't write it.

**Comment by JamyDev** [comment]
@NeatMonster Can you fix it?

**Comment by NeatMonster** [comment]
I'm trying to.

**Comment by NeatMonster** [comment]
Fixed (http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip).
