### ISSUE TITLE
Scheduler doesn't work

### ISSUE THREAD

**Issue by GoldenIrony** [XereoNet/SpaceBukkit#48]
I found some similar Ticket, but not which describes my Problem: I add something to the schedule. After i go back to the Scheduler my Schedule is still there. After restarting the server the schedule is not in the Scheduler anymore. I looked into the console and it printed this error message: 

java.io.IOException: Das System kann den angegebenen Pfad nicht finden 
        at java.io.WinNTFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(Unknown Source)
        at me.neatmonster.spacebukkitrtk.scheduler.Scheduler.saveTask(Scheduler.java:128)
        at me.neatmonster.spacebukkitrtk.scheduler.Scheduler.addTask(Scheduler.java:34)
        at me.neatmonster.spacebukkitrtk.web.Executor.addTask(Executor.java:879)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:115)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:33)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71)

If you need help with the translation:
Das System kann den angegebenen Pfad nicht finden 

Means: 
The system cannot find the specified path.

Specs as usual:

Spacebukkit v1.02
Bukkit 1597
Windows Vista Build 6001
Xampp

**Comment by NeatMonster** [comment]
Still there with v1.03?

**Comment by NeatMonster** [comment]
Fixed in the latest builds. Please download from: http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip.
