### ISSUE TITLE
Management page crashes plugin on load

### ISSUE THREAD

**Issue by dst1980** [XereoNet/SpaceBukkit#60]
In the console:

Exception in thread "Thread-33" java.lang.NullPointerException
        at me.neatmonster.spacebukkitrtk.web.Executor.listFiles(Executor.java:490)
        at me.neatmonster.spacebukkitrtk.web.Executor.getAllWorlds(Executor.java:930)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:113)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:33)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71)

This occurs as soon as the authentication for a user is attempted. As long as no one is signing in, this works.

**Comment by NeatMonster** [comment]
Please try my latest build: http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip

**Comment by Grinch** [comment]
I still get this when going to Plugins.

16:41:34 [SEVERE] Exception in thread "Thread-401"
16:41:34 [SEVERE] java.lang.NullPointerException
16:41:34 [SEVERE]       at me.neatmonster.spacebukkit.web.Executor.getPluginInformations(Executor.java:587)
16:41:34 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.checkMethod(Interpretator.java:113)
16:41:34 [SEVERE]       at me.neatmonster.spacebukkit.web.Interpretator.interpret(Interpretator.java:45)
16:41:34 [SEVERE]       at me.neatmonster.spacebukkit.listeners.Listener.run(Listener.java:57)

**Comment by dst1980** [comment]
This has fixed my problem.  @NinjaGrinch : Make sure you remove/overwrite the previous version(s) of the plugins.  Multiple copies with different names could cause problems.

**Comment by Grinch** [comment]
I have. It died when I went to the Plugins page. :|

**Comment by Grinch** [comment]
I also get this when removing the default schedule on the Schedules tab (do they even work yet?)

Exception in thread "Thread-55" java.lang.NumberFormatException: For input string: "$id"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:481)
        at java.lang.Integer.valueOf(Integer.java:582)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:118)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:33)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71)

**Comment by JamyDev** [comment]
NinjaGrinch please make seperate issues. Closing this one..
