### ISSUE TITLE
Errors with plugin and cp wont load

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#63]
I recently updated to v1.0.4. Whenever I launch the server, I get this.

2011-12-28 04:44:21 [WARNING] Task of 'SpaceBukkit' generated an exception
java.lang.NoSuchMethodError: org.json.JSONArray.size()I
    at me.neatmonster.spacebukkit.utilities.Utilities.getBukkitDevName(Utilities.java:294)
    at me.neatmonster.spacebukkit.utilities.Checker.run(Checker.java:21)
    at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:137)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:493)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

I am using NeatMonster's latest build as he told in other issue report.
Also the SpaceBukkit webpanel wont load at all.

**Comment by NeatMonster** [comment]
Which OS, Java version?

**Comment by ghost** [comment]
CentOS 6
Java version 1.6.0_20

**Comment by NeatMonster** [comment]
OK.

Edit: I opened a thread on Bukkit because I can't figure it out by myself: http://forums.bukkit.org/threads/52045/

**Comment by NeatMonster** [comment]
Please try http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip, it may solve your issue.

**Comment by NeatMonster** [comment]
http://dl.dropbox.com/u/34835222/SpaceBukkit/latest.zip will solve you issue, I promise.
