### ISSUE TITLE
Removing default schedule results in Exception

### ISSUE THREAD

**Issue by Grinch** [XereoNet/SpaceBukkit#65]
I get this when removing the default schedule on the Schedules tab (does the Scheduler feature even work yet? :))

Exception in thread "Thread-22" java.lang.NumberFormatException: For input string: "$id"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:481)
        at java.lang.Integer.valueOf(Integer.java:582)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:118)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:33)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71

**Comment by NeatMonster** [comment]
@Antariano @JamyDev This is an issue with panel. I don't think $id is a valid number. :D

**Comment by JamyDev** [comment]
I'll check it out this evening ;)
On Dec 28, 2011 10:54 AM, "NeatMonster" <
reply@reply.github.com>
wrote:

**Comment by NeatMonster** [comment]
OK.

**Comment by JamyDev** [comment]
Fixed for 1.05
