### ISSUE TITLE
NPE when deleting plugin

### ISSUE THREAD

**Issue by Lolmewn** [XereoNet/SpaceBukkit#85]
Exception in thread "Thread-39" java.lang.NullPointerException
        at me.neatmonster.spacebukkitrtk.utilities.Utilities.getPluginFile(Utilities.java:211)
        at me.neatmonster.spacebukkitrtk.web.Executor.pluginRemove(Executor.java:911)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.checkMethod(Interpretator.java:93)
        at me.neatmonster.spacebukkitrtk.web.Interpretator.interpret(Interpretator.java:20)
        at me.neatmonster.spacebukkitrtk.listeners.Listener.run(Listener.java:71
)

This is one of my own plugins, not released. It didn't get removed. And this was shown on the web-end after some freeze time:
Fatal error: Maximum execution time of 30 seconds exceeded in D:\xampp\htdocs\space\app\SpaceBukkitAPI.php on line 102

**Comment by Lolmewn** [comment]
Never mind, #82 is the same.
