### ISSUE TITLE
SpaceBukkit Module nor plugin will lauch (Gives errors)

### ISSUE THREAD

**Issue by ghost** [XereoNet/SpaceBukkit#94]
2012-01-28 00:36:58 [SEVERE] java.net.ConnectException: Connection timed out
2012-01-28 00:36:58 [SEVERE]     at java.net.PlainSocketImpl.socketConnect(Native Method)
2012-01-28 00:36:58 [SEVERE]     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:327)
2012-01-28 00:36:58 [SEVERE]     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:193)
2012-01-28 00:36:58 [SEVERE]     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:180)
2012-01-28 00:36:58 [SEVERE]     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:384)
2012-01-28 00:36:58 [SEVERE]     at java.net.Socket.connect(Socket.java:546)
2012-01-28 00:36:58 [SEVERE]     at java.net.Socket.connect(Socket.java:495)
2012-01-28 00:36:58 [SEVERE]     at sun.net.NetworkClient.doConnect(NetworkClient.java:178)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.http.HttpClient.openServer(HttpClient.java:409)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.http.HttpClient.openServer(HttpClient.java:530)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.http.HttpClient.<init>(HttpClient.java:240)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.http.HttpClient.New(HttpClient.java:321)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.http.HttpClient.New(HttpClient.java:338)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:935)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:876)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:801)
2012-01-28 00:36:58 [SEVERE]     at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1139)
2012-01-28 00:36:58 [SEVERE]     at me.neatmonster.spacebukkit.utilities.Utilities.isValidLicense(Utilities.java:123)
2012-01-28 00:36:58 [SEVERE]     at me.neatmonster.spacebukkit.SpaceBukkit.onEnable(SpaceBukkit.java:54)
2012-01-28 00:36:58 [SEVERE]     at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:188)
2012-01-28 00:36:58 [SEVERE]     at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:968)
2012-01-28 00:36:58 [SEVERE]     at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
2012-01-28 00:36:58 [SEVERE]     at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:186)
2012-01-28 00:36:58 [SEVERE]     at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:169)
2012-01-28 00:36:58 [SEVERE]     at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:348)
2012-01-28 00:36:58 [SEVERE]     at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:335)
2012-01-28 00:36:58 [SEVERE]     at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:165)
2012-01-28 00:36:58 [SEVERE]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:399)
2012-01-28 00:36:58 [SEVERE]     at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2012-01-28 00:36:58 [SEVERE] ----------------------------------------------------------
2012-01-28 00:36:58 [SEVERE] | License invalid or expired! See spacebukkit.xereo.net. |
2012-01-28 00:36:58 [SEVERE] ----------------------------------------------------------
2012-01-28 00:36:58 [INFO] ----------------------------------------------------------
2012-01-28 00:36:58 [INFO] |             SpaceBukkit is now disabled!               |
2012-01-28 00:36:58 [INFO] ----------------------------------------------------------

SpaceBukkit is just running fine on my other server which is running the 1.1RB (1818), but the server I've got running 1.0RB (1597) gives me this error.
It also does whine about the Module. Whats up with it?

**Comment by Antariano** [comment]
Thanks, we're on it

**Comment by NeatMonster** [comment]
Jamy's server was down, issue closed.
